#!/usr/bin/env python3
"""Generate stable CSV and JavaScript views from ontology/anatomy.yaml."""

from __future__ import annotations

import csv
import json
from pathlib import Path

import yaml


ROOT = Path(__file__).resolve().parents[1]


def load() -> list[dict]:
    return yaml.safe_load((ROOT / "ontology/anatomy.yaml").read_text())["objects"]


def record(item: dict) -> dict:
    codepoint = str(item["unicode_pua"]).upper()
    return {
        "id": item["id"],
        "label": item["label"],
        "category": item["category"],
        "system": item["system"],
        "parent": item.get("parent"),
        "paired": bool(item.get("paired", False)),
        "laterality_supported": bool(item.get("laterality_supported", False)),
        "laterality": item.get("laterality"),
        "aliases": item.get("aliases", []),
        "codepoint": f"U+{codepoint}",
        "char": chr(int(codepoint, 16)),
        "ligature": item["ligature"],
        "shortcode": item["shortcode"],
        "glyph_name": "anatomy_" + item["id"].split(":", 1)[1],
        "glyph_base": item["glyph"]["base"],
        "svg": item["glyph"]["monochrome"],
        "color_svg": item["glyph"]["color"],
        "external_ids": item.get("external_ids", {}),
        "sources": item.get("sources", []),
        "accessible_label": item["label"],
    }


def write_csv(path: Path, rows: list[dict], fields: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)


def main() -> int:
    rows = [record(item) for item in load()]
    write_csv(ROOT / "registry/codepoints.csv", rows, ["id", "label", "category", "system", "codepoint", "char", "glyph_name", "svg", "color_svg"])
    write_csv(ROOT / "registry/ligatures.csv", rows, ["id", "label", "ligature", "glyph_name", "codepoint"])
    aliases = []
    for row in rows:
        aliases.append({"id": row["id"], "alias": row["label"], "kind": "label"})
        aliases.append({"id": row["id"], "alias": row["shortcode"], "kind": "shortcode"})
        aliases.extend({"id": row["id"], "alias": alias, "kind": "alias"} for alias in row["aliases"])
    write_csv(ROOT / "registry/aliases.csv", aliases, ["id", "alias", "kind"])

    package_rows = [{key: value for key, value in row.items() if key != "char"} | {"char": row["char"]} for row in rows]
    package = """/** Generated by scripts/generate_registry.py. */\nconst registry = %s;\nconst byId = new Map(registry.map((item) => [item.id, item]));\nconst byShortcode = new Map(registry.map((item) => [item.shortcode, item]));\nfunction get(id) { return byId.get(id) || null; }\nfunction resolveShortcode(shortcode) { return byShortcode.get(shortcode) || null; }\nfunction unicodeFor(id) { const item = get(id); return item ? item.char : null; }\nfunction search(query) { const needle = String(query || '').toLowerCase(); return registry.filter((item) => [item.id, item.label, item.shortcode, ...item.aliases].some((value) => String(value).toLowerCase().includes(needle))); }\nmodule.exports = { registry, get, resolveShortcode, unicodeFor, search };\n""" % json.dumps(package_rows, ensure_ascii=False, indent=2)
    (ROOT / "packages/js/index.js").write_text(package, encoding="utf-8")
    (ROOT / "packages/js/index.d.ts").write_text("""export interface AnatomyRecord {\n  id: string; label: string; category: 'bone' | 'organ' | 'tissue'; system: string;\n  parent: string | null; paired: boolean; laterality_supported: boolean; laterality: 'left' | 'right' | null;\n  aliases: string[]; codepoint: string; char: string; ligature: string; shortcode: string; glyph_name: string;\n  glyph_base: string; svg: string; color_svg: string; external_ids: Record<string, string>; sources: string[]; accessible_label: string;\n}\nexport const registry: AnatomyRecord[];\nexport function get(id: string): AnatomyRecord | null;\nexport function resolveShortcode(shortcode: string): AnatomyRecord | null;\nexport function unicodeFor(id: string): string | null;\nexport function search(query: string): AnatomyRecord[];\n""", encoding="utf-8")
    docs_data = json.dumps(package_rows, ensure_ascii=False)
    (ROOT / "docs/registry.js").write_text(f"window.BONES_REGISTRY = {docs_data};\n", encoding="utf-8")
    print(f"generated registries and JS metadata for {len(rows)} objects")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
